name: Deploy to OpenShift Sandbox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # 🔹 Login to Docker Hub
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 🔹 Build Image
    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .

    # 🔹 Push Image
    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

    # 🔹 Install oc CLI
    - name: Install OpenShift CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        tar -xvf oc.tar.gz
        sudo mv oc /usr/local/bin

    # 🔹 Login to OpenShift
    - name: Login to OpenShift
      run: |
        oc login ${{ secrets.OPENSHIFT_SERVER }} \
          --token=${{ secrets.OPENSHIFT_TOKEN }} \
          --insecure-skip-tls-verify=true

        oc project ${{ secrets.OPENSHIFT_NAMESPACE }}

    # 🔹 Deploy App (First time + updates)
    - name: Deploy to OpenShift
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

        sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" k8s/deployment.yaml

        oc apply -f k8s/deployment.yaml
        oc apply -f k8s/service.yaml

        oc expose svc my-app || true
